server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://10.1.1.235:3308/tps_points?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: update  #自动更新
      show-sql: true      #日志中显示sql语句




  #redis:
  #    host: 119.23.71.201
  #    prot: 6379
  #cloud:
  #  config:
  #   label: master         # 远程仓库的分支
  #    discovery:
  #      enabled: true               #开启配置服务发现
  #      service-id: qb-config          #配置服务实例名称
      #uri: http://localhost:7777/
      #profile: dev          # 和git里的文件名对应
   #     name: config-client-dev
