server:
  port: 8888

spring:
  datasource:
    url:  jdbc:mysql://bdm269683585.my3w.com:3306/bdm269683585?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: bdm269683585
    password: bdm269683585
    driver-class-name: com.mysql.jdbc.Driver
  redis:
      host: 119.23.71.201
      prot: 6379
  cloud:
    config:
      label: master         # 远程仓库的分支
      discovery:
        enabled: true               #开启配置服务发现
        service-id: qb-config          #配置服务实例名称
      #uri: http://localhost:7777/
      #profile: dev          # 和git里的文件名对应
        name: config-client-dev
