server:
  port: 8777

spring:
  datasource:
    url: jdbc:mysql://10.1.1.235:3308/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: tps138dev
    password: F52o0QJCg8@L
    #type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#      hibernate:
#        ddl-auto: update  #自动更新
#      show-sql: true      #日志中显示sql语句


#mapper:
#  mappers: tk.mybatis.mapper.common.Mapper,tk.mybatis.mapper.common.MySqlMapper
#  not-empty: false
#  identity: MYSQL
#  check-example-entity-class: true

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yd.bo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名转换
    map-underscore-to-camel-case: true

  #redis:
  #    host: 119.23.71.201
  #    prot: 6379
  #cloud:
  #  config:
  #   label: master         # 远程仓库的分支
  #    discovery:
  #      enabled: true               #开启配置服务发现
  #      service-id: qb-config          #配置服务实例名称
      #uri: http://localhost:7777/
      #profile: dev          # 和git里的文件名对应
   #     name: config-client-dev
